### ISSUE TITLE
Découpage des images pour la chasse aux parasites

### ISSUE THREAD

**Issue by pierrepo** [fongwama/EduPalu#25]
Dans le jeu "chasse aux parasites", les images de goutte épaisse ou de frottis devraient être découpées automatiquement en fonction de la place disponible sur l'écran.

@steve111MV peux-tu faire quelque chose ?

**Comment by steve111MV** [comment]
ok pierre, sorry for the 3 days disparution. as i am attending a formation here, i have to be more focused. from after tomorrow all will go fatser

**Comment by pierrepo** [comment]
No probs @steve111MV  I know you were busy these days ;-)

**Comment by pierrepo** [comment]
@steve111MV nice work!
Could you then fix the number of visible parasites to find? And the adapt the scoring scheme?

**Comment by PrinceYoulou** [comment]
@pierrepo satisfied with the game play so far? it's a work in progress the game play is the next challenge

**Comment by pierrepo** [comment]
@steve111MV @steve111MV 
Could you now : 
- hide (not delete, user css display : none) buttons "cacher" et "recommencer"
- add a button "quitter" that link to the home page
- compute the number of visible parasites on the picture and set a timer to 5 seconds x the number of visible parasites (-> 20 seconds for 4 parasites, 30 seconds for 6 parasites)

**Comment by steve111MV** [comment]
Yes Pierre, i am on it. give me 72h max.
