### ISSUE TITLE
Take off placeholder 

### ISSUE THREAD

**Issue by PrinceYoulou** [fongwama/EduPalu#58]
The placeholder "brazza" must be replaced by "Recherche" in the page Pharmacies

**Comment by pierrepo** [comment]
There is no placeholder (removed some time ago).

Could you add a real placeholder ("Indiquez ici un nom, une adresse, une ville...") with the placeholder attribut?
Could you also remove the label "NOM, ADRESSE, VILLE" that will not be useful anymore?
