### ISSUE TITLE
Chasse au parasites front-end

### ISSUE THREAD

**Issue by steve111MV** [fongwama/EduPalu#60]
@pierrepo  c'est bon la couleur du texte sur le button 'Suivant" ?

**Comment by pierrepo** [comment]
Non, le texte devrait être blanc.
Peux-tu essayer de corriger cela (regarde comment les autres boutons son codés) ?

**Comment by steve111MV** [comment]
sorry, didn't see your question, should use @steve111MV as you tauch me. :-)

@pierrepo

**Comment by pierrepo** [comment]
Normally you should have received an e-mail when I answer to one of your message...
